language: java
services:
  - postgresql
before_script:
  - psql -c "create database 'hotel-api';" -U postgres
  - psql -c "create user 'hotel-user' with password 'hotel-api-spring-boot';" -U postgres
  - psql -c "grant all privileges on database 'hotel-api' to 'hotel-user';" -U postgres
